version: '3.8'
services:
  api:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: let-it-tree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - 5432:5432