version: '3.8'
services:
  db:
    image: postgres:16.0-alpine
    container_name: db
    environment:
      POSTGRES_DB: let-it-tree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
  api:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/let-it-tree
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update